### ISSUE TITLE
Cannot find Module '../structures/music/erela'

### ISSUE THREAD

**Issue by Wolf-FiveM** [FirezTheGreat/Hope#2]
`Require stack:`
`Hope\structures\Hope.js`
`Hope\index.js`

at new Hope (C:\Hope\structures\Hope.js:26:22)
at Object.<anonymous> (C:\Hope\index.js:4:13)

`code: 'MODULE_NOT_FOUND',`
  `requireStack: [`
    `'C:\\Users\\Lyric\\Desktop\\Rizon\\structures\\Hope.js',`
    `'C:\\Users\\Lyric\\Desktop\\Rizon\\index.js'`

**Comment by FirezTheGreat** [comment]
Music support was removed in v2

**Comment by FirezTheGreat** [comment]
wait nvm let me fix

**Comment by FirezTheGreat** [comment]
[remove that line and it will be fine](https://github.com/FirezTheGreat/Hope/commit/ad4f288400ec142740d73dde28cb72dbaa8d6881)
